scalar DateTime @scalar(class: "Nuwave\\Lighthouse\\Schema\\Types\\Scalars\\DateTime")

type Query {
    songs: [Song!]!
    countries: [Country!]!
    song(id: ID!): Song
}

type Mutation {
    createCountry(input: CreateCountryInput!): Country
}

type Country {
    id: ID!
    name: String!
    email: String!
    password: String!
    created_at: DateTime!
    updated_at: DateTime!
}

type Song {
    id: ID!
    title: String!
    artist: String!
    year: Int!
    country_id: ID!
    created_at: DateTime!
    updated_at: DateTime!
}

type Vote {
    id: ID!
    televote: Boolean!
    from_country_id: ID!
    to_song_id: ID!
    points: Int!
    created_at: DateTime!
    updated_at: DateTime!
}
